[2016-07-06 11:48:55,117] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:48:56,011] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:48:56,141] {models.py:1196} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2016-07-06 11:48:56,188] {models.py:1219} INFO - Executing <Task(BashOperator): run_scripts> on 2015-06-05 00:00:00
[2016-07-06 11:48:56,217] {bash_operator.py:55} INFO - tmp dir root location: 
/tmp
[2016-07-06 11:48:56,218] {bash_operator.py:64} INFO - Temporary script location :/tmp/airflowtmp5HlYWF//tmp/airflowtmp5HlYWF/run_scripts1gAjM5
[2016-07-06 11:48:56,219] {bash_operator.py:65} INFO - Running command: cat ~/opa_data/'br65trf.os13sd' | python properties.py > properties.csv
  cat ~/opa_data/'br63trf.buildcod' | python building_codes.py > /tmp/tmpVPos3J/building_codes.csv
  cat ~/opa_data/'br63trf.stcode' | python street_codes.py > /tmp/tmpVPos3J/street_codes.csv
  cat ~/opa_data/'br63trf.offpr' | python off_property.py > /tmp/tmpVPos3J/off_property.csv
  cat ~/opa_data/'br63trf.nicrt4wb' | python assessment_history.py > /tmp/tmpVPos3J/assessment_history.csv
[2016-07-06 11:48:56,221] {bash_operator.py:73} INFO - Output:
[2016-07-06 11:48:56,227] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br65trf.os13sd: No such file or directory
[2016-07-06 11:48:56,232] {bash_operator.py:77} INFO - python: can't open file 'properties.py': [Errno 2] No such file or directory
[2016-07-06 11:48:56,235] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.buildcod: No such file or directory
[2016-07-06 11:48:56,242] {bash_operator.py:77} INFO - python: can't open file 'building_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:48:56,246] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.stcode: No such file or directory
[2016-07-06 11:48:56,251] {bash_operator.py:77} INFO - python: can't open file 'street_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:48:56,255] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.offpr: No such file or directory
[2016-07-06 11:48:56,261] {bash_operator.py:77} INFO - python: can't open file 'off_property.py': [Errno 2] No such file or directory
[2016-07-06 11:48:56,267] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.nicrt4wb: No such file or directory
[2016-07-06 11:48:56,270] {bash_operator.py:77} INFO - python: can't open file 'assessment_history.py': [Errno 2] No such file or directory
[2016-07-06 11:48:56,270] {bash_operator.py:80} INFO - Command exited with return code 2
[2016-07-06 11:48:56,271] {models.py:1286} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1245, in run
    result = task_copy.execute(context=context)
  File "/home/nwebz/venv/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 83, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2016-07-06 11:48:56,272] {models.py:1298} INFO - Marking task as UP_FOR_RETRY
[2016-07-06 11:48:56,322] {models.py:1327} ERROR - Bash command failed
[2016-07-06 11:54:01,945] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:54:02,840] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:54:02,951] {models.py:1196} INFO - 
--------------------------------------------------------------------------------
Starting attempt 2 of 2
--------------------------------------------------------------------------------

[2016-07-06 11:54:03,025] {models.py:1219} INFO - Executing <Task(BashOperator): run_scripts> on 2015-06-05 00:00:00
[2016-07-06 11:54:03,049] {bash_operator.py:55} INFO - tmp dir root location: 
/tmp
[2016-07-06 11:54:03,050] {bash_operator.py:64} INFO - Temporary script location :/tmp/airflowtmphQUpZv//tmp/airflowtmphQUpZv/run_scriptsLeMyDU
[2016-07-06 11:54:03,050] {bash_operator.py:65} INFO - Running command: cat ~/opa_data/'br65trf.os13sd' | python properties.py > properties.csv
  cat ~/opa_data/'br63trf.buildcod' | python building_codes.py > /tmp/tmpVPos3J/building_codes.csv
  cat ~/opa_data/'br63trf.stcode' | python street_codes.py > /tmp/tmpVPos3J/street_codes.csv
  cat ~/opa_data/'br63trf.offpr' | python off_property.py > /tmp/tmpVPos3J/off_property.csv
  cat ~/opa_data/'br63trf.nicrt4wb' | python assessment_history.py > /tmp/tmpVPos3J/assessment_history.csv
[2016-07-06 11:54:03,053] {bash_operator.py:73} INFO - Output:
[2016-07-06 11:54:03,059] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br65trf.os13sd: No such file or directory
[2016-07-06 11:54:03,062] {bash_operator.py:77} INFO - python: can't open file 'properties.py': [Errno 2] No such file or directory
[2016-07-06 11:54:03,067] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.buildcod: No such file or directory
[2016-07-06 11:54:03,071] {bash_operator.py:77} INFO - python: can't open file 'building_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:54:03,075] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.stcode: No such file or directory
[2016-07-06 11:54:03,080] {bash_operator.py:77} INFO - python: can't open file 'street_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:54:03,086] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.offpr: No such file or directory
[2016-07-06 11:54:03,089] {bash_operator.py:77} INFO - python: can't open file 'off_property.py': [Errno 2] No such file or directory
[2016-07-06 11:54:03,095] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.nicrt4wb: No such file or directory
[2016-07-06 11:54:03,098] {bash_operator.py:77} INFO - python: can't open file 'assessment_history.py': [Errno 2] No such file or directory
[2016-07-06 11:54:03,099] {bash_operator.py:80} INFO - Command exited with return code 2
[2016-07-06 11:54:03,099] {models.py:1286} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1245, in run
    result = task_copy.execute(context=context)
  File "/home/nwebz/venv/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 83, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2016-07-06 11:54:03,100] {models.py:1304} INFO - All retries failed; marking task as FAILED
[2016-07-06 11:54:03,105] {models.py:1311} ERROR - Failed to send email to: ['airflow@airflow.com']
[2016-07-06 11:54:03,105] {models.py:1312} ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1308, in handle_failure
    self.email_alert(error, is_retry=False)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1425, in email_alert
    send_email(task.email, title, body)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/utils/email.py", line 43, in send_email
    return backend(to, subject, html_content, files=files, dryrun=dryrun)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/utils/email.py", line 79, in send_email_smtp
    send_MIME_email(SMTP_MAIL_FROM, to, msg, dryrun)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/utils/email.py", line 91, in send_MIME_email
    s = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) if SMTP_SSL else smtplib.SMTP(SMTP_HOST, SMTP_PORT)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[2016-07-06 11:54:03,145] {models.py:1327} ERROR - Bash command failed
