[2016-07-06 11:49:01,021] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:49:01,941] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:49:02,060] {models.py:1196} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2016-07-06 11:49:02,117] {models.py:1219} INFO - Executing <Task(BashOperator): run_scripts> on 2015-06-04 00:00:00
[2016-07-06 11:49:02,144] {bash_operator.py:55} INFO - tmp dir root location: 
/tmp
[2016-07-06 11:49:02,146] {bash_operator.py:64} INFO - Temporary script location :/tmp/airflowtmp7Vnjd3//tmp/airflowtmp7Vnjd3/run_scripts35NfvV
[2016-07-06 11:49:02,147] {bash_operator.py:65} INFO - Running command: cat ~/opa_data/'br65trf.os13sd' | python properties.py > properties.csv
  cat ~/opa_data/'br63trf.buildcod' | python building_codes.py > /tmp/tmpgs97J8/building_codes.csv
  cat ~/opa_data/'br63trf.stcode' | python street_codes.py > /tmp/tmpgs97J8/street_codes.csv
  cat ~/opa_data/'br63trf.offpr' | python off_property.py > /tmp/tmpgs97J8/off_property.csv
  cat ~/opa_data/'br63trf.nicrt4wb' | python assessment_history.py > /tmp/tmpgs97J8/assessment_history.csv
[2016-07-06 11:49:02,150] {bash_operator.py:73} INFO - Output:
[2016-07-06 11:49:02,156] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br65trf.os13sd: No such file or directory
[2016-07-06 11:49:02,164] {bash_operator.py:77} INFO - python: can't open file 'properties.py': [Errno 2] No such file or directory
[2016-07-06 11:49:02,171] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.buildcod: No such file or directory
[2016-07-06 11:49:02,176] {bash_operator.py:77} INFO - python: can't open file 'building_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:49:02,182] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.stcode: No such file or directory
[2016-07-06 11:49:02,188] {bash_operator.py:77} INFO - python: can't open file 'street_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:49:02,192] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.offpr: No such file or directory
[2016-07-06 11:49:02,200] {bash_operator.py:77} INFO - python: can't open file 'off_property.py': [Errno 2] No such file or directory
[2016-07-06 11:49:02,207] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.nicrt4wb: No such file or directory
[2016-07-06 11:49:02,213] {bash_operator.py:77} INFO - python: can't open file 'assessment_history.py': [Errno 2] No such file or directory
[2016-07-06 11:49:02,214] {bash_operator.py:80} INFO - Command exited with return code 2
[2016-07-06 11:49:02,215] {models.py:1286} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1245, in run
    result = task_copy.execute(context=context)
  File "/home/nwebz/venv/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 83, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2016-07-06 11:49:02,216] {models.py:1298} INFO - Marking task as UP_FOR_RETRY
[2016-07-06 11:49:02,229] {models.py:1327} ERROR - Bash command failed
[2016-07-06 11:54:07,865] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:54:08,649] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:54:08,758] {models.py:1196} INFO - 
--------------------------------------------------------------------------------
Starting attempt 2 of 2
--------------------------------------------------------------------------------

[2016-07-06 11:54:08,814] {models.py:1219} INFO - Executing <Task(BashOperator): run_scripts> on 2015-06-04 00:00:00
[2016-07-06 11:54:08,837] {bash_operator.py:55} INFO - tmp dir root location: 
/tmp
[2016-07-06 11:54:08,838] {bash_operator.py:64} INFO - Temporary script location :/tmp/airflowtmpn2KeHM//tmp/airflowtmpn2KeHM/run_scriptspiae4A
[2016-07-06 11:54:08,838] {bash_operator.py:65} INFO - Running command: cat ~/opa_data/'br65trf.os13sd' | python properties.py > properties.csv
  cat ~/opa_data/'br63trf.buildcod' | python building_codes.py > /tmp/tmpgs97J8/building_codes.csv
  cat ~/opa_data/'br63trf.stcode' | python street_codes.py > /tmp/tmpgs97J8/street_codes.csv
  cat ~/opa_data/'br63trf.offpr' | python off_property.py > /tmp/tmpgs97J8/off_property.csv
  cat ~/opa_data/'br63trf.nicrt4wb' | python assessment_history.py > /tmp/tmpgs97J8/assessment_history.csv
[2016-07-06 11:54:08,842] {bash_operator.py:73} INFO - Output:
[2016-07-06 11:54:08,847] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br65trf.os13sd: No such file or directory
[2016-07-06 11:54:08,851] {bash_operator.py:77} INFO - python: can't open file 'properties.py': [Errno 2] No such file or directory
[2016-07-06 11:54:08,855] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.buildcod: No such file or directory
[2016-07-06 11:54:08,860] {bash_operator.py:77} INFO - python: can't open file 'building_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:54:08,867] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.stcode: No such file or directory
[2016-07-06 11:54:08,869] {bash_operator.py:77} INFO - python: can't open file 'street_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:54:08,875] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.offpr: No such file or directory
[2016-07-06 11:54:08,878] {bash_operator.py:77} INFO - python: can't open file 'off_property.py': [Errno 2] No such file or directory
[2016-07-06 11:54:08,883] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.nicrt4wb: No such file or directory
[2016-07-06 11:54:08,887] {bash_operator.py:77} INFO - python: can't open file 'assessment_history.py': [Errno 2] No such file or directory
[2016-07-06 11:54:08,888] {bash_operator.py:80} INFO - Command exited with return code 2
[2016-07-06 11:54:08,888] {models.py:1286} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1245, in run
    result = task_copy.execute(context=context)
  File "/home/nwebz/venv/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 83, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2016-07-06 11:54:08,889] {models.py:1304} INFO - All retries failed; marking task as FAILED
[2016-07-06 11:54:08,894] {models.py:1311} ERROR - Failed to send email to: ['airflow@airflow.com']
[2016-07-06 11:54:08,894] {models.py:1312} ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1308, in handle_failure
    self.email_alert(error, is_retry=False)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1425, in email_alert
    send_email(task.email, title, body)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/utils/email.py", line 43, in send_email
    return backend(to, subject, html_content, files=files, dryrun=dryrun)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/utils/email.py", line 79, in send_email_smtp
    send_MIME_email(SMTP_MAIL_FROM, to, msg, dryrun)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/utils/email.py", line 91, in send_MIME_email
    s = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) if SMTP_SSL else smtplib.SMTP(SMTP_HOST, SMTP_PORT)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[2016-07-06 11:54:08,907] {models.py:1327} ERROR - Bash command failed
