[2016-07-06 11:49:07,025] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:49:08,116] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:49:08,247] {models.py:1196} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2016-07-06 11:49:08,302] {models.py:1219} INFO - Executing <Task(BashOperator): run_scripts> on 2015-06-07 00:00:00
[2016-07-06 11:49:08,331] {bash_operator.py:55} INFO - tmp dir root location: 
/tmp
[2016-07-06 11:49:08,332] {bash_operator.py:64} INFO - Temporary script location :/tmp/airflowtmpQURWFt//tmp/airflowtmpQURWFt/run_scriptsN2BOMp
[2016-07-06 11:49:08,332] {bash_operator.py:65} INFO - Running command: cat ~/opa_data/'br65trf.os13sd' | python properties.py > properties.csv
  cat ~/opa_data/'br63trf.buildcod' | python building_codes.py > /tmp/tmpLQlsNt/building_codes.csv
  cat ~/opa_data/'br63trf.stcode' | python street_codes.py > /tmp/tmpLQlsNt/street_codes.csv
  cat ~/opa_data/'br63trf.offpr' | python off_property.py > /tmp/tmpLQlsNt/off_property.csv
  cat ~/opa_data/'br63trf.nicrt4wb' | python assessment_history.py > /tmp/tmpLQlsNt/assessment_history.csv
[2016-07-06 11:49:08,334] {bash_operator.py:73} INFO - Output:
[2016-07-06 11:49:08,339] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br65trf.os13sd: No such file or directory
[2016-07-06 11:49:08,344] {bash_operator.py:77} INFO - python: can't open file 'properties.py': [Errno 2] No such file or directory
[2016-07-06 11:49:08,347] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.buildcod: No such file or directory
[2016-07-06 11:49:08,353] {bash_operator.py:77} INFO - python: can't open file 'building_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:49:08,359] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.stcode: No such file or directory
[2016-07-06 11:49:08,363] {bash_operator.py:77} INFO - python: can't open file 'street_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:49:08,367] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.offpr: No such file or directory
[2016-07-06 11:49:08,372] {bash_operator.py:77} INFO - python: can't open file 'off_property.py': [Errno 2] No such file or directory
[2016-07-06 11:49:08,375] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.nicrt4wb: No such file or directory
[2016-07-06 11:49:08,380] {bash_operator.py:77} INFO - python: can't open file 'assessment_history.py': [Errno 2] No such file or directory
[2016-07-06 11:49:08,381] {bash_operator.py:80} INFO - Command exited with return code 2
[2016-07-06 11:49:08,381] {models.py:1286} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1245, in run
    result = task_copy.execute(context=context)
  File "/home/nwebz/venv/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 83, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2016-07-06 11:49:08,382] {models.py:1298} INFO - Marking task as UP_FOR_RETRY
[2016-07-06 11:49:08,432] {models.py:1327} ERROR - Bash command failed
[2016-07-06 11:54:13,923] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:54:14,706] {models.py:154} INFO - Filling up the DagBag from /home/nwebz/airflow/dags/clean_opa.py
[2016-07-06 11:54:14,815] {models.py:1196} INFO - 
--------------------------------------------------------------------------------
Starting attempt 2 of 2
--------------------------------------------------------------------------------

[2016-07-06 11:54:14,880] {models.py:1219} INFO - Executing <Task(BashOperator): run_scripts> on 2015-06-07 00:00:00
[2016-07-06 11:54:14,904] {bash_operator.py:55} INFO - tmp dir root location: 
/tmp
[2016-07-06 11:54:14,906] {bash_operator.py:64} INFO - Temporary script location :/tmp/airflowtmpWKsNKZ//tmp/airflowtmpWKsNKZ/run_scriptsyBaSRD
[2016-07-06 11:54:14,906] {bash_operator.py:65} INFO - Running command: cat ~/opa_data/'br65trf.os13sd' | python properties.py > properties.csv
  cat ~/opa_data/'br63trf.buildcod' | python building_codes.py > /tmp/tmpLQlsNt/building_codes.csv
  cat ~/opa_data/'br63trf.stcode' | python street_codes.py > /tmp/tmpLQlsNt/street_codes.csv
  cat ~/opa_data/'br63trf.offpr' | python off_property.py > /tmp/tmpLQlsNt/off_property.csv
  cat ~/opa_data/'br63trf.nicrt4wb' | python assessment_history.py > /tmp/tmpLQlsNt/assessment_history.csv
[2016-07-06 11:54:14,909] {bash_operator.py:73} INFO - Output:
[2016-07-06 11:54:14,915] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br65trf.os13sd: No such file or directory
[2016-07-06 11:54:14,919] {bash_operator.py:77} INFO - python: can't open file 'properties.py': [Errno 2] No such file or directory
[2016-07-06 11:54:14,923] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.buildcod: No such file or directory
[2016-07-06 11:54:14,928] {bash_operator.py:77} INFO - python: can't open file 'building_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:54:14,934] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.stcode: No such file or directory
[2016-07-06 11:54:14,938] {bash_operator.py:77} INFO - python: can't open file 'street_codes.py': [Errno 2] No such file or directory
[2016-07-06 11:54:14,943] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.offpr: No such file or directory
[2016-07-06 11:54:14,949] {bash_operator.py:77} INFO - python: can't open file 'off_property.py': [Errno 2] No such file or directory
[2016-07-06 11:54:14,955] {bash_operator.py:77} INFO - cat: /home/nwebz/opa_data/br63trf.nicrt4wb: No such file or directory
[2016-07-06 11:54:14,959] {bash_operator.py:77} INFO - python: can't open file 'assessment_history.py': [Errno 2] No such file or directory
[2016-07-06 11:54:14,959] {bash_operator.py:80} INFO - Command exited with return code 2
[2016-07-06 11:54:14,960] {models.py:1286} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1245, in run
    result = task_copy.execute(context=context)
  File "/home/nwebz/venv/lib/python2.7/site-packages/airflow/operators/bash_operator.py", line 83, in execute
    raise AirflowException("Bash command failed")
AirflowException: Bash command failed
[2016-07-06 11:54:14,961] {models.py:1304} INFO - All retries failed; marking task as FAILED
[2016-07-06 11:54:14,966] {models.py:1311} ERROR - Failed to send email to: ['airflow@airflow.com']
[2016-07-06 11:54:14,967] {models.py:1312} ERROR - [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1308, in handle_failure
    self.email_alert(error, is_retry=False)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/models.py", line 1425, in email_alert
    send_email(task.email, title, body)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/utils/email.py", line 43, in send_email
    return backend(to, subject, html_content, files=files, dryrun=dryrun)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/utils/email.py", line 79, in send_email_smtp
    send_MIME_email(SMTP_MAIL_FROM, to, msg, dryrun)
  File "/home/nwebz/venv/local/lib/python2.7/site-packages/airflow/utils/email.py", line 91, in send_MIME_email
    s = smtplib.SMTP_SSL(SMTP_HOST, SMTP_PORT) if SMTP_SSL else smtplib.SMTP(SMTP_HOST, SMTP_PORT)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused
[2016-07-06 11:54:14,979] {models.py:1327} ERROR - Bash command failed
